export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as UserHome} from './UserHome'
export {Login, Signup} from './AuthForm'
export {default as Dashboard} from './Dashboard'
export {default as Form} from './Form'
export {default as Chart} from './Chart'
export {default as Table} from './Table'
export {default as Range} from './Range'
export {default as Landing} from './Landing'
export {default as Information} from './form/Information'
export {default as Delivery} from './form/Delivery'
export {default as Gestation} from './form/Gestation'
export {default as DeliveryDate} from './form/DeliveryDate'
