export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {Login, Signup} from './AuthForm'
export {default as Dashboard} from './Dashboard'
export {default as Form} from './Form'
export {default as Chart} from './Chart'
export {default as Table} from './Table'
export {default as Sidebar} from './Sidebar'
export {default as Information} from './form/Information'
export {default as Delivery} from './form/Delivery'
export {default as Gestation} from './form/Gestation'
export {default as DeliveryDate} from './form/DeliveryDate'
export {default as ComingSoon} from './ComingSoon'
export {default as Sliders} from './Sliders'
export {default as Slider} from './Slider'
export {default as FilterDate} from './FilterDate'